### ISSUE TITLE
Questions about the hard prompt and soft prompt in your code

### ISSUE THREAD

**Issue by shaoyuyoung** [adf1178/PT4Code#13]
Hi,

I'm sorry,but limited by my code level, I still don't know how to apply prompts like those in your paper to your code.
In your code, for example,in the task of code summarization, there is a hard prompt `Generate comments for [𝐿𝐴𝑁𝐺] [𝑋] [𝑍]`. I don't know how to apply it in code. The same goes for soft prompts.

From what I understand, I'm guessing it has to do with this line of code.
```python
   promptTemplate = SoftTemplate(model=plm, tokenizer=tokenizer,
                                  text='Code: {"placeholder":"text_a"} Summarization: {"mask"} ',
                                  initialize_from_vocab=True,
                                  num_tokens=50)
```

For the parameter `text`, the value `Code: {"placeholder":"text_a"} Summarization: {"mask"}`  seems to be different from the value in your paper

**Comment by adf1178** [comment]
The template in the code is not the ones used in the paper. I did some additional experiments and forgot to modify back :(

**Comment by shaoyuyoung** [comment]
Are you willing to modify it on GitHub? Your work attracts many researchers. It seems that they also met this problem  :)

**Comment by shaoyuyoung** [comment]
The issue #8 is the same problem.

**Comment by adf1178** [comment]
Thanks for your advice and your interest in our work! The template is very easy to modify and experiment, thus I do not check the code carefully. In addition, for generation tasks, the natural language tokens in the template will affect the performance slightly. I will modify the template later.
