### ISSUE TITLE
Cannot download dataset for Code Summarization

### ISSUE THREAD

**Issue by DuckYellowPP** [adf1178/PT4Code#15]
I met a problem when I exec this command, which LANG = Ruby/Go/PHP/Java/Python/JavaScript
```
wget https://s3.amazonaws.com/code-search-net/CodeSearchNet/v2/{LANG}.zip
```

The error code is 403,
The error message is 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KY0D35ECZ6N9Y6F1</RequestId>
<HostId>1dVA91UlipsQHZWhzjF9ImHkRmg/0z2sZzlLxWLKepD3SbwWTWcarpwAYJoP/1oPPfrFnNB8f/c=</HostId>
</Error>
```

Should I register an account with Amazonaws or do something else?
Thanks!

**Comment by adf1178** [comment]
Ah, it seems that. the original codesearchnet links have something wrong. 
You can refer to CodeXGLUE project to download the dataset: https://github.com/microsoft/CodeXGLUE/tree/main/Code-Text/code-to-text

**Comment by DuckYellowPP** [comment]
Thank you for your reply. It worked.
