### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by Moshiii** [adf1178/PT4Code#4]
Hi,

Thanks for the good work. I am reproducing your work but find these files are missing : 

in codebert.py:
train_dataset = read_answers('/data/czwang/prompt/dataset/train.jsonl')
valid_dataset = read_answers('/data/czwang/prompt/dataset/valid.jsonl')
test_dataset = read_answers('/data/czwang/prompt/dataset/test.jsonl')

Can you please provide the dataset?  I download the dataset with command 

cd dataset
pip install gdown
gdown https://drive.google.com/uc?id=1x6hoF7G-tSYxg8AFybggypLZgMGDNHfF
cd ..

but it is not relevent to /data/czwang/prompt/dataset/train.jsonl or th other two.

Thanks!

**Comment by adf1178** [comment]
You can refer to Issue #3 and download datasets in CodeXGlue
