### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Moshiii** [adf1178/PT4Code#5]
I am following the #3 issue and am able to get the data, but now if I run the script defect/codebert.py
I got a Cuda runtime error. Has anyone seen this before? I checked my Cuda installation and run other models and it works.
I suspect it is the sequence length but it is already set to max_seq_length = 512.

Any help, please? greatly appreciate!

![image](https://user-images.githubusercontent.com/7553188/199168844-3cdaf8bc-b47c-4503-bc4e-c937c57e6fca.png)

**Comment by adf1178** [comment]
I do not really know the situation .. But the number of the tokenized data items is not correct ( 11it in the image, however, for normal training it should be 21k+ for tokenizing training set, 2k+ for tokenizing testing set)?  Do you modify the training data or something wrong occured in the tokenization process?
